name: Run tests and linting pipeline

on:
  push:
    branches:
      - "**"  # Run on every branch
  pull_request:
    branches:
      - "**"  # Run on every PR

jobs:
  test-lint-coverage:
    name: Run Tests, Linting, and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_test.txt

      - name: Lint Code
        run: |
          source venv/bin/activate
          flake8 src tests
          pylint src

      - name: Run Tests and Coverage
        run: |
          source venv/bin/activate
          PYTHONPATH=. pytest --cov=src --cov-fail-under=92 tests/
